export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

export const LOAD_INSURANCES_SUCCESS = 'LOAD_INSURANCES_SUCCESS';
export const CREATE_INSURANCES_SUCCESS = 'CREATE_INSURANCES_SUCCESS';
export const UPDATE_INSURANCES_SUCCESS = 'UPDATE_INSURANCES_SUCCESS';
export const DELETE_INSURANCES_SUCCESS = 'DELETE_INSURANCES_SUCCESS';